# Generated by Django 4.2.7 on 2024-01-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=260)),
                ('url', models.CharField(max_length=30)),
                ('useremail', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=230, null=True)),
                ('recipientemail', models.EmailField(max_length=254, null=True)),
                ('senderemail', models.EmailField(max_length=254, null=True)),
                ('amount', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('description', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('recipientemail', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(max_length=230)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Recipients',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('useremail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('description', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('recipientemail', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(max_length=230)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=230)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50, null=True)),
                ('balance', models.DecimalField(
                    decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
