# Generated by Django 4.2.7 on 2024-01-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepepay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image_url',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification',
            field=models.CharField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='useremail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
