# Generated by Django 4.2.7 on 2024-01-15 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pepepay', '0002_users_image_url_alter_notifications_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='senderemail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='sendername',
            field=models.CharField(default=django.utils.timezone.now, max_length=230),
            preserve_default=False,
        ),
    ]
